version: '3.3'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --workers=8 --error-logfile '-' --access-logfile '-' --access-logformat '%(t)s "%(r)s" %(s)s %(b)s' config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ~/projects_data/armax/static/:/app/static
      - ~/projects_data/armax/media/:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/projects_data/armax/pgdata:/var/lib/postgresql/data/
    env_file:
      - .env.db
  nginx:
    restart: unless-stopped
    build: ./nginx
    volumes:
      - ~/projects_data/armax/static/:/app/static
      - ~/projects_data/armax/media/:/app/media
      - ./certbot/www:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
volumes:
  pgdata:
  static_volume:
  certbot:
