version: '3.3'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver [::]:8000
    volumes:
      - ~/project/static/:/app/static
      - ~/project/media/:/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/project/pgdata:/var/lib/postgresql/data/
    env_file:
      - .env.db
  nginx:
    restart: unless-stopped
    build: ./nginx
    volumes:
      - ~/project/static/:/app/static
      - ~/project/media/:/app/media
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  pgdata:
  static_volume:
