# Generated by Django 4.2 on 2023-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_request_niche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='niche',
            field=models.IntegerField(blank=True, choices=[(1, 'Веб'), (2, 'Мобильное приложение'), (3, 'Десктопное приложение'), (4, 'Кроссплатформенное приложение')], null=True, verbose_name='Ниша'),
        ),
    ]
